openapi: 3.0.0
info:
  title: API GastroFlow - Módulo de Entradas de Estoque
  description: CRUD para gerenciamento de Entradas de produtos no estoque.
  version: 1.0.0
servers:
  - url: http://localhost:5000/v1/api
    description: Servidor Local (porta 5000 configurada no application.properties)

security:
  - bearerAuth: []

paths:
  /entradas:
    # POST /entradas - Criar Entrada
    post:
      tags:
        - Entradas
      summary: Cria uma nova entrada de produto no estoque.
      operationId: createEntrada
      security:
        - bearerAuth: [ADMIN, STANDARD] # Restrição de segurança
      requestBody:
        description: Dados da nova Entrada
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntradaRequestDTO'
      responses:
        '201':
          description: Entrada cadastrada com sucesso!
        '400':
          description: Requisição inválida (Produto/Usuário/Fornecedor não encontrado ou dados incorretos)
        '403':
          description: Acesso negado (Token inválido ou nível de acesso insuficiente)

    # GET /entradas - Buscar Entrada por ID
    get:
      tags:
        - Entradas
      summary: Busca uma entrada pelo ID.
      operationId: getEntradaById
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID da Entrada (Long)
      responses:
        '200':
          description: Sucesso. Retorna a Entrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntradaResponseDTO'
        '404':
          description: Entrada não encontrada

    # PATCH /entradas - Atualizar Entrada
    patch:
      tags:
        - Entradas
      summary: Atualiza os dados de uma entrada existente.
      operationId: updateEntradaById
      security:
        - bearerAuth: [ADMIN, STANDARD]
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID da Entrada a ser atualizada (Long)
      requestBody:
        description: Novos dados da Entrada
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntradaRequestDTO'
      responses:
        '200':
          description: Entrada atualizada com sucesso!
        '404':
          description: Entrada não encontrada
        '403':
          description: Acesso negado

    # DELETE /entradas - Deletar Entrada
    delete:
      tags:
        - Entradas
      summary: Deleta uma entrada pelo ID.
      operationId: deleteEntradaById
      security:
        - bearerAuth: [ADMIN]
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID da Entrada a ser deletada (Long)
      responses:
        '204':
          description: Entrada deletada com sucesso! (No Content)
        '404':
          description: Entrada não encontrada

  /entradas/todas:
    # GET /entradas/todas - Listar todas
    get:
      tags:
        - Entradas
      summary: Lista todas as entradas cadastradas.
      operationId: findAllEntradas
      responses:
        '200':
          description: Sucesso. Retorna a lista de Entradas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntradaResponseDTO'

  /entradas/produto:
    # GET /entradas/produto - Buscar por ID do Produto
    get:
      tags:
        - Entradas
      summary: Busca entradas pelo ID do produto.
      operationId: getAllByProdutoId
      parameters:
        - in: query
          name: produtoId
          schema:
            type: integer
            format: int64
          required: true
          description: ID do Produto associado (Long)
      responses:
        '200':
          description: Sucesso. Retorna a lista de Entradas do produto.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntradaResponseDTO'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Coloque o JWT (token) aqui para autenticação.

  schemas:
    EntradaRequestDTO:
      type: object
      properties:
        dataEntrada:
          type: string
          format: date-time
          description: Data da entrada no estoque.
          example: '2025-10-27T10:00:00.000Z'
        quantidade:
          type: integer
          description: Quantidade de produto que entrou.
          example: 10
        observacao:
          type: string
          nullable: true
          description: Observações sobre a entrada (opcional).
          example: Compra de emergência para o evento de Natal.
        produtoId:
          type: integer
          format: int64
          description: ID do Produto (Long).
          example: 1
        fornecedorId:
          type: string
          format: uuid
          nullable: true
          description: ID do Fornecedor (UUID - Opcional, conforme EntradaDTO).
          example: 'a1b2c3d4-e5f6-7890-1234-567890abcdef'
        userId:
          type: string
          format: uuid
          description: ID do Usuário responsável (UUID).
          example: 'b9a8b7a6-5d4c-3e2f-1098-7654321fedcba'
      required:
        - dataEntrada
        - quantidade
        - produtoId
        - userId

    EntradaResponseDTO:
      allOf:
        - $ref: '#/components/schemas/EntradaRequestDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              description: ID gerado da Entrada.
              example: 101