openapi: 3.0.0
info:
  title: GastroFlow API - Módulo Entradas
  description: API para gerenciamento de Entradas/Recebimento de Estoque com suporte a múltiplos produtos por entrada (EntradaProduto).
  version: 1.0.0

servers:
  - url: http://localhost:5000/v1/api
    description: Servidor Local (GastroFlow API Base)

security:
  - bearerAuth: [] # Aplica a segurança JWT globalmente

tags:
  - name: Entradas
    description: Operações de CRUD para Entradas de Estoque

paths:
  /entradas:
    # ----------------------------------------------------
    # POST /entradas - Criar Entrada
    # ----------------------------------------------------
    post:
      tags:
        - Entradas
      summary: Cria uma nova entrada de estoque, podendo conter múltiplos produtos.
      operationId: createEntrada
      security:
        - bearerAuth: []
      requestBody:
        description: Dados da Entrada a ser criada, incluindo a lista de produtos.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntradaDTO'
            example:
              dataEntrada: "2025-11-10T10:00:00Z"
              observacao: "Nota fiscal 9876. Lote especial de cervejas."
              fornecedorId: 1
              preco: 12000
              produtos:
                - produtoId: 101
                  quantidade: 50
                - produtoId: 102
                  quantidade: 10
      responses:
        '201':
          description: Entrada criada com sucesso.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    # ----------------------------------------------------
    # PATCH /entradas - Atualizar Entrada
    # ----------------------------------------------------
    patch:
      tags:
        - Entradas
      summary: Atualiza uma entrada de estoque existente (data, observação, fornecedor, preço).
      description: |
        **Nota Importante:** Este endpoint só atualiza os campos principais da `Entrada`. 
        A atualização de produtos requer outro endpoint específico.
      operationId: updateEntradaById
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID da Entrada a ser atualizada.
      requestBody:
        description: Dados da Entrada a serem atualizados.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntradaDTO'
            example:
              dataEntrada: "2025-11-10T11:30:00Z"
              observacao: "Observação corrigida. Nota fiscal 9876."
              fornecedorId: 1
              preco: 12500
      responses:
        '200':
          description: Entrada atualizada com sucesso.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    # ----------------------------------------------------
    # DELETE /entradas - Deletar Entrada
    # ----------------------------------------------------
    delete:
      tags:
        - Entradas
      summary: Deleta uma entrada de estoque pelo ID.
      operationId: deleteEntradaById
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID da Entrada a ser deletada.
      responses:
        '204':
          description: Entrada deletada com sucesso (No Content).
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    # ----------------------------------------------------
    # GET /entradas?id={id} - Buscar Entrada por ID
    # ----------------------------------------------------
    get:
      tags:
        - Entradas
      summary: Busca uma entrada de estoque pelo ID.
      operationId: getEntradaById
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID da Entrada.
      responses:
        '200':
          description: Entrada encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntradaReturnDTO'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /entradas/todas:
    get:
      tags:
        - Entradas
      summary: Lista todas as entradas de estoque registradas.
      operationId: findAllEntradas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de todas as entradas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntradaReturnDTO'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /entradas/produto:
    get:
      tags:
        - Entradas
      summary: Lista todas as entradas que contêm um produto específico pelo ID do produto.
      operationId: getAllEntradasByProdutoId
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: produtoId
          schema:
            type: integer
            format: int64
          required: true
          description: ID do Produto.
      responses:
        '200':
          description: Lista de entradas encontradas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntradaReturnDTO'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Nenhuma entrada encontrada para o produto especificado.

components:
  schemas:
    EntradaProdutoItemDTO:
      type: object
      properties:
        produtoId:
          type: integer
          format: int64
          example: 101
        quantidade:
          type: integer
          example: 50
      required:
        - produtoId
        - quantidade

    EntradaDTO:
      type: object
      properties:
        dataEntrada:
          type: string
          format: date-time
          example: "2025-11-10T10:00:00Z"
        observacao:
          type: string
          nullable: true
          example: "Lote A"
        fornecedorId:
          type: integer
          format: int64
          nullable: true
          example: 1
        preco:
          type: integer
          format: int64
          nullable: true
          example: 12000
        produtos:
          type: array
          items:
            $ref: '#/components/schemas/EntradaProdutoItemDTO'
      required:
        - dataEntrada
        - produtos

    EntradaReturnDTO:
      allOf:
        - $ref: '#/components/schemas/EntradaDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
            userId:
              type: string
              format: uuid
              example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"

    Error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Coloque o JWT aqui para autorização.

  responses:
    NotFound:
      description: Recurso não encontrado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Requisição inválida (dados malformados ou faltando).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Não autorizado (Token JWT inválido ou faltando).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
