openapi: 3.0.0
info:
  title: GastroFlow API - Módulo Retiradas
  description: API para gerenciamento de Retiradas (saídas) de Estoque, com IDs Long.
  version: 1.0.0
servers:
  - url: http://localhost:5000/v1/api
    description: Servidor de Desenvolvimento Local

security:
  - bearerAuth: [] # Aplica a segurança JWT globalmente

tags:
  - name: Retiradas
    description: Operações de CRUD para Saídas de Estoque

paths:
  /retiradas:
    # ----------------------------------------------------
    # POST /retiradas - Criar Retirada
    # ----------------------------------------------------
    post:
      tags:
        - Retiradas
      summary: Registra uma nova saída (retirada) de produto do estoque.
      operationId: createRetirada
      security:
        - bearerAuth: [] # Requer JWT
      requestBody:
        description: Dados da Retirada a ser registrada.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetiradaDTO'
            example:
              dataRetirada: "2025-10-25T14:30:00Z"
              quantidade: 5
              observacao: "Uso na cozinha principal"
              produtoId: 101 # ID do Produto (Long)
              userId: "4f4e7e6a-2d4e-4e6a-9a9e-2f2e5e4a7a8b" # ID do Usuário (UUID)
      responses:
        '201':
          description: Retirada registrada com sucesso.
        '400':
          description: Requisição inválida (Produto não encontrado ou estoque insuficiente).
        '403':
          description: Acesso negado (Usuário sem papel 'ADMIN' ou 'STANDARD').

    # ----------------------------------------------------
    # PATCH /retiradas?id={id} - Atualizar Retirada por ID
    # ----------------------------------------------------
    patch:
      tags:
        - Retiradas
      summary: Atualiza uma retirada de produto existente pelo ID.
      operationId: updateRetiradaById
      security:
        - bearerAuth: [] # Requer JWT
      parameters:
        - name: id
          in: query
          description: ID da Retirada a ser atualizada (Long).
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados da Retirada a serem atualizados.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetiradaDTO'
            example:
              dataRetirada: "2025-10-25T15:00:00Z"
              quantidade: 6
              observacao: "Correção: Uso na cozinha principal"
              produtoId: 101
              userId: "4f4e7e6a-2d4e-4e6a-9a9e-2f2e5e4a7a8b"
      responses:
        '200':
          description: Retirada atualizada com sucesso.
        '404':
          description: Retirada ou Produto/Usuário não encontrado.
        '403':
          description: Acesso negado (Usuário sem papel 'ADMIN' ou 'STANDARD').

    # ----------------------------------------------------
    # GET /retiradas?id={id} - Buscar Retirada por ID (Query Param)
    # ----------------------------------------------------
    get:
      tags:
        - Retiradas
      summary: Busca uma retirada por ID (Long).
      operationId: getRetiradaById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          description: ID da Retirada (Long).
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retirada encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetiradaDTO'
        '404':
          description: Retirada não encontrada.

    # ----------------------------------------------------
    # DELETE /retiradas?id={id} - Deletar Retirada por ID
    # ----------------------------------------------------
    delete:
      tags:
        - Retiradas
      summary: Deleta uma retirada por ID (Long).
      operationId: deleteRetiradaById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          description: ID da Retirada a ser deletada (Long).
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Retirada deletada com sucesso.
        '404':
          description: Retirada não encontrada.
        '403':
          description: Acesso negado (Usuário sem papel 'ADMIN').

  /retiradas/todas:
    # ----------------------------------------------------
    # GET /retiradas/todas - Listar todas as Retiradas
    # ----------------------------------------------------
    get:
      tags:
        - Retiradas
      summary: Lista todas as retiradas de estoque.
      operationId: findAllRetiradas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de retiradas retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RetiradaDTO'

  /retiradas/produto:
    # ----------------------------------------------------
    # GET /retiradas/produto?produtoId={produtoId} - Buscar por ID do Produto
    # ----------------------------------------------------
    get:
      tags:
        - Retiradas
      summary: Busca retiradas pelo ID do produto.
      operationId: getAllByProdutoId
      security:
        - bearerAuth: []
      parameters:
        - name: produtoId
          in: query
          description: ID do Produto (Long) para filtrar as retiradas.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista de entradas para o produto encontrado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RetiradaDTO'

components:
  schemas:
    RetiradaDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da Retirada (apenas para retorno/referência).
        dataRetirada:
          type: string
          format: date-time
          description: Data e hora da retirada do produto.
        quantidade:
          type: integer
          description: Quantidade de produto que saiu do estoque.
        observacao:
          type: string
          nullable: true
          description: Observações sobre a retirada.
        produtoId:
          type: integer
          format: int64
          description: ID do Produto relacionado (Long).
        userId:
          type: string
          format: uuid
          description: ID do Usuário que registrou a retirada (UUID).
      required:
        - dataRetirada
        - quantidade
        - produtoId
        - userId

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Coloque o Token JWT (somente o token, sem 'Bearer ')